
import Image from "next/image";
import Link from "next/link";

export const metadata = { title: "About" };

export default function AboutPage() {
  return <main><section className="page-hero"><div className="page-hero-media"><Image src="/fackts/events/culture-crowd.webp" alt="FACKTS people together" fill priority sizes="100vw" /></div><div className="shell page-hero-content"><div className="eyebrow">About FACKTS Africa Group</div><h1 className="mega tight">BORN IN KENYA.<br/>BUILT FOR AFRICA.<br/>MADE FOR THE WORLD.</h1></div></section><section className="about-origin"><div className="shell about-origin-grid"><h2 className="display">NOT A BASKETBALL COMPANY.<br/>NOT A MUSIC COMPANY.<br/>A CULTURE GROUP.</h2><div className="origin-copy"><p>FACKTS Africa Group operates where basketball, music, creators, athletes, communities, storytelling, live experiences, brands, technology and talent development meet. Hoops and Music are the first major engines. They are not the entire ceiling.</p><p style={{marginTop:24}}>The company builds environments where people can be discovered, documented, organized, experienced and connected to opportunity — while brands and institutions enter through outcomes that are useful to them.</p></div></div></section><section className="about-values"><div className="shell"><div className="eyebrow">Operating logic</div><div style={{marginTop:38}}><div className="value-line"><b>01</b><h3>Diagnose the real problem.</h3><p>Start with what is actually weak or missing in the ecosystem, not what sounds impressive on a pitch deck.</p></div><div className="value-line"><b>02</b><h3>Know who benefits.</h3><p>The user, beneficiary and payer may be three different people. Build the product around that truth.</p></div><div className="value-line"><b>03</b><h3>Focus before expansion.</h3><p>Hoops and Music stay coherent enough to become strong engines before the group adds noise.</p></div><div className="value-line"><b>04</b><h3>Systemize what proves itself.</h3><p>Successful activity becomes a format, workflow or property rather than permanent founder hustle.</p></div><div className="value-line"><b>05</b><h3>Build, test, learn, travel.</h3><p>Kenya is the root. The operating language should become strong enough to travel across African cities and into the diaspora.</p></div></div><div style={{marginTop:38}}><Link className="btn-line" href="/partners">Build with the group <span className="arrow">→</span></Link></div></div></section></main>;
}
