import LegalLayout from "@/components/LegalLayout";
import { siteConfig } from "@/lib/content";

export const metadata = {
  title: { absolute: "Privacy & Data Protection | FACKTS Africa Group" },
  description:
    "FACKTS Africa privacy and data protection notice covering website, player, creator, event, media, booking and partner-related personal data in Kenya.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <LegalLayout
      eyebrow="Legal / privacy"
      title="PRIVACY & DATA PROTECTION."
      intro="This notice explains the personal data FACKTS may handle across its group website, platforms, events, profiles, creator projects, media activity, bookings and partnerships, and the rights available to data subjects under Kenyan law."
      updated="16 September 2026"
    >
      <section>
        <h2>1. Our privacy principle</h2>
        <p>
          FACKTS aims to collect personal data for a lawful, specific and explained
          purpose, use only what is reasonably necessary, protect it appropriately
          and keep it only for as long as the purpose or law reasonably requires.
          This approach reflects the right to privacy under Article 31 of the
          Constitution of Kenya and the principles of the Data Protection Act 2019.
        </p>
      </section>

      <section>
        <h2>2. Data we may handle</h2>
        <ul>
          <li>Contact and identity information such as name, email, phone, age or age band where necessary.</li>
          <li>Player, team and game information used in FACKTS Hoops profiles and records.</li>
          <li>Creator, project, session, contribution and credit information used in FACKTS Music.</li>
          <li>Event registration, participation, competition, consent and release records.</li>
          <li>Photography, video, audio, interviews and other recorded media.</li>
          <li>Partnership, booking, enquiry, supplier and commercial correspondence.</li>
          <li>Technical information reasonably generated by websites, hosting, security, analytics or embedded-media services.</li>
        </ul>
      </section>

      <section>
        <h2>3. Why we use personal data</h2>
        <p>
          We may use personal data to operate player and creator profiles, administer
          games and events, manage projects and credits, respond to enquiries,
          deliver contracted services, maintain consent and participation records,
          publish authorised media, protect platform security, improve services,
          meet legal obligations and preserve a legitimate cultural or operational
          archive where lawful.
        </p>
      </section>

      <section>
        <h2>4. Lawful bases</h2>
        <p>
          The lawful basis depends on the activity. It may include consent,
          performance of or steps toward a contract, compliance with a legal
          obligation, protection of vital interests, legitimate interests that do
          not improperly override individual rights, or another ground permitted by
          Kenyan law. Where consent is the basis, FACKTS must be able to demonstrate
          it and consent may be withdrawn.
        </p>
      </section>

      <section>
        <h2>5. Recorded media</h2>
        <p>
          Photography, video and audio can identify a person and may therefore be
          personal data. FACKTS applies the separate <a href="/consent">Media & Recording Consent Policy</a>.
          Featured interviews, portraits and participant-focused content may require
          specific consent or a contractual media term. Event-wide recording should
          be accompanied by appropriate notice and practical opt-out arrangements
          where applicable.
        </p>
      </section>

      <section>
        <h2>6. Children and young participants</h2>
        <p>
          Personal data relating to a child requires stronger safeguards. Where
          required, FACKTS obtains parent or guardian consent, uses age-verification
          measures appropriate to the context and processes the data in a manner
          that protects and advances the child's rights and best interests. A child's
          privacy, dignity and maturity should be considered when deciding what to
          publish even where a guardian has consented.
        </p>
      </section>

      <section>
        <h2>7. Health and rehabilitation information</h2>
        <p>
          Health data is sensitive. FACKTS does not need detailed clinical records
          simply because a health or rehabilitation partner participates in the
          ecosystem. Clinical information should remain with the relevant healthcare
          provider unless a lawful, necessary and appropriately protected reason
          requires otherwise. A referral or event-health workflow should disclose
          only what is necessary for the relevant purpose.
        </p>
      </section>

      <section>
        <h2>8. Insurance information</h2>
        <p>
          Where a person chooses to engage an insurance partner, quotations,
          underwriting information, policy records and claims material are handled
          under the applicable insurer or intermediary process. FACKTS should not
          receive detailed insurance information unless it is necessary for a
          specific lawful purpose and the person has been properly informed.
        </p>
      </section>

      <section>
        <h2>9. Partners and service providers</h2>
        <p>
          FACKTS may use independent providers for hosting, communications, media,
          production, event operations, technology and specialist services. We do
          not treat a partnership as permission for unrestricted data sharing. Data
          should only be shared where there is a lawful purpose, a suitable role and
          appropriate safeguards. Independent partners may also act as separate data
          controllers for their own services.
        </p>
      </section>

      <section>
        <h2>10. International services and transfers</h2>
        <p>
          Some hosting, cloud, analytics, communication or embedded-media providers
          may process data outside Kenya. Where an international transfer is made,
          FACKTS should use the safeguards required by Kenyan data-protection law and
          pay particular attention to sensitive personal data.
        </p>
      </section>

      <section>
        <h2>11. Retention</h2>
        <p>
          FACKTS does not set one blanket retention period for every category of
          data. Records are retained only for as long as reasonably necessary for
          the purpose, contractual or legal needs, disputes, consent evidence,
          legitimate archives or another lawful basis. Data that is no longer
          necessary should be deleted, anonymised, pseudonymised or otherwise
          handled in accordance with law.
        </p>
      </section>

      <section>
        <h2>12. Your rights</h2>
        <p>
          Kenyan data-protection law gives data subjects rights including being
          informed about use of personal data, access, objection, correction and
          deletion in applicable circumstances. Additional rights can include
          restriction, portability and protections around solely automated
          decision-making. Rights involving a minor may be exercised by a person
          with parental authority or a guardian as provided by law.
        </p>
      </section>

      <section>
        <h2>13. Consent withdrawal and objections</h2>
        <p>
          Where processing relies on consent, you may withdraw that consent. The
          withdrawal does not make earlier lawful processing unlawful, but FACKTS
          should stop future consent-based processing unless another lawful basis
          applies. Requests relating to published media are handled under the Media
          & Recording Consent Policy.
        </p>
      </section>

      <section>
        <h2>14. Security</h2>
        <p>
          FACKTS should use reasonable technical and organisational safeguards
          appropriate to the data and risk involved, including access controls,
          role-based access where relevant, secure platform configuration and
          disciplined handling of files and credentials. No internet system can be
          guaranteed to be risk-free.
        </p>
      </section>

      <section>
        <h2>15. Requests and complaints</h2>
        <p>
          Send a privacy, correction, access, deletion, objection or consent request
          to <a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a> with enough
          information for us to identify the relevant record. You may also have the
          right to raise a complaint with Kenya's Office of the Data Protection
          Commissioner.
        </p>
      </section>
    </LegalLayout>
  );
}
